In [1]:
# Import Dependencies and CSV File
import pandas as pd

# restaurants_csv = pd.read_csv("../Resources/az_yelp_business.csv")
restaurants_csv = pd.read_csv("../Resources/az_yelp_restaurants.csv")
restaurants_csv.head()

,name,address,city,state,postal_code,latitude,longitude,stars,review_count,categories
0,"""McDonald's""","""719 E Thunderbird Rd""",Phoenix,AZ,85022,33.607070,-112.064382,1.0,10,Fast Food;Burgers;Restaurants
1,"""Charr An American Burger Bar""","""777 E Thunderbird Rd, Ste 107""",Phoenix,AZ,85022,33.607310,-112.063404,3.0,232,Burgers;Restaurants
2,"""McDonald's""","""1635 E Camelback Rd""",Phoenix,AZ,85016,33.508765,-112.046240,3.0,34,Restaurants;Burgers;Fast Food
3,"""Little Caesars Pizza""","""10720 E Southern Ave""",Mesa,AZ,85209,33.394877,-111.600194,2.5,4,Restaurants;Pizza
4,"""Caviness Studio""","""""",Phoenix,AZ,85001,33.449967,-112.070222,5.0,4,Marketing;Men's Clothing;Restaurants;Graphic D...

In [3]:
### Dataframe Display Options
# pd.set_option('display.max_rows', None)
# pd.reset_option('display.max_rows')

In [2]:
# Filter out for only restaurants
rest = restaurants_csv.loc[restaurants_csv['categories'].str.lower().str.contains("restaurant")].reset_index(drop=True)
# Remove paranthesis
rest['name'] = rest['name'].str.replace('"','')
rest['address'] = rest['address'].str.replace('"','')
# Drop categories NA
rest['categories'] = rest['categories'].dropna()
# Lowercase categories for easier use
rest['categories'] = rest['categories'].str.lower().astype(str)

In [3]:
# Remove non-restaurants
notRest = 'marketing|clothing|shops|advertising|schools|lakes|shopping|printing|convenience stores|yelp|grocery|golf|cafeteria|food court|stadiums & arenas|supernatural readings|veterinarians|hotels|event planning & services|hospitals|home services|markets|spas|adult entertainment|trucks|cinema'
rests = rest.loc[rest['categories'].str.contains(notRest)==False]

In [4]:
def newCat(x):
    '''
    Function to clean and group categories into major category groupings.
    '''
    cat = x['categories']
    if 'american' in cat:
        return "American"
    elif 'italian' in cat:
        return "Italian"
    elif 'japanese' in cat:
        return "Japanese"
    elif 'mexican' in cat:
        return "Mexican"
    elif 'chinese' in cat:
        return "Chinese"
    elif 'viet' in cat:
        return "Vietnamese"
    elif 'mediterranean' in cat:
        return 'Mediterranean'
    elif 'hawaiian' in cat:
        return 'Hawaiian'
    elif 'thai' in cat:
        return 'Thai'
    elif 'pizza' in cat:
        return 'Italian'
    elif 'greek' in cat:
        return 'Mediterranean'
    elif 'indian' in cat:
        return 'Indian'
    elif 'asian fusion' in cat:
        return 'Asian Fusion'
    elif 'filipino' in cat:
        return 'Filipino'
    elif 'coffee & tea' in cat:
        return 'American'
    elif 'burgers' in cat:
        return 'American'
    elif 'sandwiches' in cat:
        return 'American'
    elif 'barbeque' in cat:
        return 'American'
    elif 'sushi' in cat:
        return 'Japanese'
    elif 'hot dogs' in cat:
        return 'American'
    elif 'steakhouses' in cat:
        return 'American'
    elif 'chicken wings' in cat:
        return 'American'
    elif 'middle eastern' in cat:
        return 'Middle Eastern'
    elif 'cajun' in cat:
        return 'American'
    elif 'fish & chips' in cat:
        return 'American'
    elif 'french' in cat:
        return 'French'
    elif 'korean' in cat:
        return 'Korean'
    elif 'cuban' in cat:
        return 'Cuban'
    elif 'diner' in cat:
        return 'American'
    elif 'deli' in cat:
        return 'American'
    elif 'peruvian' in cat:
        return 'American'
    elif 'tex-mex' in cat:
        return 'Mexican'
    elif 'ice cream & frozen yogurt' in cat:
        return 'American'
    elif 'caribbean' in cat:
        return 'Caribbean'
    elif 'soul food' in cat:
        return 'American'
    elif 'german' in cat:
        return 'German'
    elif 'cafes' in cat:
        return 'American'
    elif 'buffets' in cat:
        return 'American'
    elif 'seafood' in cat:
        return 'American'
    elif 'sports bar' in cat:
        return 'American'
    elif 'dive' in cat:
        return 'American'
    elif 'spanish' in cat:
        return 'Spanish'
    elif 'chicken shop' in cat:
        return 'American'
    elif 'juice bars & smoothies' in cat:
        return 'American'
    elif 'tapas' in cat:
        return 'Mexican'
    elif 'ethiopian' in cat:
        return 'Ethiopian'
    elif 'irish' in cat:
        return 'Irish'
    elif 'russian' in cat:
        return 'Russian'
    elif 'vegetarian' in cat:
        return 'American'
    elif 'bakeries' in cat:
        return 'American'
    elif 'polish' in cat:
        return 'Polish'
    elif 'cambodian' in cat:
        return 'Cambodian'
    elif 'british' in cat:
        return 'British'
    elif 'southern' in cat:
        return 'American'
    elif 'comfort food' in cat:
        return 'American'
    elif 'mongolian' in cat:
        return 'Mongolian'
    elif 'persian' in cat:
        return 'Persian'
    elif 'european' in cat:
        return 'European'
    elif 'turkish' in cat:
        return 'Turkish'
    elif 'burmese' in cat:
        return 'Burmese'
    elif 'brazilian' in cat:
        return 'Brazilian'
    elif 'kosher' in cat:
        return 'Kosher'
    elif 'afghan' in cat:
        return 'Middle Eastern'
    elif 'halal' in cat:
        return 'Halal'
    elif 'czech' in cat:
        return 'Czech'
    elif 'african' in cat:
        return 'African'
    else:
        return 'American'

# Create new Category Column using the newCat Function
rests['category'] = rests.apply(lambda x: newCat(x),axis=1)

<ipython-input-4-1c6c34b34560>:142: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rests['category'] = rests.apply(lambda x: newCat(x),axis=1)

In [5]:
rests['category'].value_counts().to_frame()

                category
American            5154
Italian             1427
Mexican             1390
Chinese              567
Japanese             353
Mediterranean        259
Thai                 142
Indian               114
Vietnamese           111
Hawaiian              56
Asian Fusion          51
French                25
Middle Eastern        25
Caribbean             22
Irish                 17
Korean                15
Filipino              10
Spanish                9
Cuban                  8
German                 8
British                7
Ethiopian              7
Polish                 5
Turkish                3
African                2
Brazilian              1
Kosher                 1
European               1
Burmese                1
Russian                1
Persian                1
Mongolian              1
Czech                  1

In [ ]:
# Create Cleaned Restaurants Csv File
rests.to_csv("../Resources/az_yelp_restaurants_categories_grouped.csv",index=False)

In [16]:
# Create Cleaned Restaurants Json File
rests.to_json("../Resources/az_yelp_restaurants2.json", orient="records")